"""Level 2 backtest — Cash-Secured Puts on the 5 basket ETFs.

Same three-phase structure as `level2.py` (MANAGE → GUARD → ENTER) but the
vehicle is a single short put per trade and the universe is SPY/QQQ/IWM/
GLD/TLT. Capital is treated as pretend $250K — one SPY CSP at a ~$500
strike reserves ~$50K, so realistic capital levels on this pipeline require
an index-sized account. The dissertation backtest scope is live-engineering
only (not written up); this is a feasibility experiment.

Walk-forward RV forecasts come from `etf_predictions.parquet` (LogHAR,
pooled across ETFs — generated by `theta.modeling.loghar_etf`). VRP is
computed the same way as the equity backtest: `atm_iv^2 - y_pred`.
"""
from __future__ import annotations

from datetime import date
from pathlib import Path
from typing import Any

import polars as pl

from theta.backtest import data as bt_data
from theta.backtest import signal as bt_signal
from theta.backtest import csp as bt_csp
from theta.backtest.csp_portfolio import (
    COMMISSION_HALF,
    CspPortfolio,
    CspPosition,
    ExitReason,
)

# $250,000 pretend capital — large enough to carry 4-5 concurrent ETF CSPs.
STARTING_CAPITAL = 100_000.0
ETF_UNIVERSE = ["SPY", "QQQ", "IWM", "GLD", "TLT"]

ETF_PREDS_PATH = bt_data.ROOT / "processed" / "evaluation" / "walk_forward" / "etf_predictions.parquet"
TRADE_LOG_FILE = bt_data.OUTPUT_DIR / "level2_csp_trade_log.parquet"
EQUITY_FILE = bt_data.OUTPUT_DIR / "level2_csp_daily_equity.parquet"


# ----- candidate assembly ------------------------------------------------

def _load_etf_predictions() -> pl.DataFrame:
    df = pl.read_parquet(ETF_PREDS_PATH)
    return df.select("symbol", "date", "y_true", "y_pred", "window_id")


def _daily_signals_etf() -> pl.DataFrame:
    """Per-(symbol, date) frame for the 5 ETFs with everything the signal
    pipeline needs. Excludes `days_to_earnings` / `is_earnings_week` —
    ETFs have no earnings.
    """
    preds = _load_etf_predictions()

    feat_frames = [
        bt_data.load_features(sym).select(
            "symbol", "date", "atm_iv", "is_fomc_week",
        )
        for sym in ETF_UNIVERSE
    ]
    feats = pl.concat(feat_frames)
    macro = bt_data.load_macro().select("date", "vix")

    return (
        preds
        .join(feats, on=["symbol", "date"], how="inner")
        .join(macro, on="date", how="inner")
        .sort(["date", "symbol"])
    )


def _apply_filters_etf(df: pl.DataFrame,
                       vix_min: float, vix_max: float) -> pl.DataFrame:
    """Filters applicable to index ETFs only — no earnings gate."""
    return df.filter(
        (pl.col("vrp") > 0)
        & pl.col("hist_median_vrp").is_not_null()
        & (pl.col("vrp") > pl.col("hist_median_vrp"))
        & (pl.col("vix") >= vix_min)
        & (pl.col("vix") <= vix_max)
        & (pl.col("is_fomc_week") == 0)
    )


def build_candidates_etf(vix_min: float = 14.0,
                         vix_max: float = 30.0) -> pl.DataFrame:
    """VRP → hist-median → filter → rank for the 5 ETFs."""
    daily = _daily_signals_etf()
    return (
        daily
        .pipe(bt_signal.add_vrp)
        .pipe(bt_signal.add_historical_median_vrp)
        .pipe(_apply_filters_etf, vix_min=vix_min, vix_max=vix_max)
        .pipe(bt_signal.rank_candidates)
    )


# ----- chain cache -------------------------------------------------------

class _ChainCache:
    """Lazy per-symbol options_iv cache with raw-EOD fallback on quote."""
    def __init__(self) -> None:
        self._by_symbol: dict[str, pl.DataFrame] = {}

    def chain(self, symbol: str) -> pl.DataFrame:
        if symbol not in self._by_symbol:
            self._by_symbol[symbol] = bt_data.load_options_iv(symbol)
        return self._by_symbol[symbol]

    def puts_on(self, symbol: str, on_date: date) -> pl.DataFrame:
        return self.chain(symbol).filter(
            (pl.col("date") == on_date) & (pl.col("right") == "PUT")
        )

    def quote(self, symbol: str, on_date: date, strike: float,
              expiration_date: date) -> dict | None:
        df = self.chain(symbol).filter(
            (pl.col("date") == on_date)
            & (pl.col("strike") == strike)
            & (pl.col("expiration_date") == expiration_date)
            & (pl.col("right") == "PUT")
        )
        if df.height > 0:
            row = df.row(0, named=True)
            return {
                "bid": row["bid"], "ask": row["ask"],
                "underlying_price": row["underlying_price"],
                "delta": row["delta"], "dte": row["dte"],
            }
        return bt_data.get_quote(
            symbol, on_date, strike, expiration_date, right="PUT",
            fallback_to_raw=True,
        )

    def underlying_on(self, symbol: str, on_date: date) -> float | None:
        df = self.chain(symbol).filter(pl.col("date") == on_date)
        if df.height == 0:
            return None
        return float(df["underlying_price"][0])


# ----- phases ------------------------------------------------------------

def _phase_a_manage(portfolio: CspPortfolio, today: date, vix: float,
                    cache: _ChainCache) -> None:
    for pos in list(portfolio.open_positions):
        if today >= pos.expiration_date:
            spot = cache.underlying_on(pos.symbol, pos.expiration_date)
            if spot is None:
                spot = pos.underlying_price
                if spot is None:
                    continue
            portfolio.settle_expiration(pos, float(spot))
            continue

        q = cache.quote(pos.symbol, today, pos.contract.strike, pos.contract.expiration_date)
        if q is None:
            continue
        pos.mark(today, q)

    marked = [p for p in portfolio.open_positions if p.as_of == today]
    for pos in marked:
        reason = portfolio._check_triggers(pos, today, vix)
        if reason is None:
            continue
        if reason == ExitReason.EXPIRATION:
            portfolio.settle_expiration(pos, float(pos.underlying_price or 0))
        else:
            portfolio.close_position(pos, today, reason)


def _phase_c_enter(portfolio: CspPortfolio, today: date,
                   day_candidates: pl.DataFrame,
                   cache: _ChainCache,
                   target_delta: float,
                   min_premium_yield: float) -> int:
    if portfolio.available_slots == 0:
        return 0

    opened = 0
    for row in day_candidates.sort("vrp_rank").iter_rows(named=True):
        if portfolio.available_slots == 0:
            break

        sym = row["symbol"]
        day_puts = cache.puts_on(sym, today)
        if day_puts.height == 0:
            continue

        contract = bt_csp.build_csp(
            sym, today, chain=day_puts,
            target_delta=target_delta,
            min_premium_yield=min_premium_yield,
        )
        if contract is None:
            continue

        if not portfolio.can_open(contract, today):
            continue
        if portfolio.available_cash <= COMMISSION_HALF:
            continue

        portfolio.add_position(contract)
        opened += 1

    return opened


# ----- orchestrator -------------------------------------------------------

def run_level2_csp(starting_capital: float = STARTING_CAPITAL,
                   target_delta: float = bt_csp.TARGET_DELTA,
                   min_premium_yield: float = bt_csp.MIN_PREMIUM_YIELD,
                   stop_loss_mult: float | None = 2.0,
                   profit_target_frac: float | None = 0.50,
                   vix_min: float = 14.0,
                   vix_max: float = 30.0,
                   save: bool = True,
                   verbose: bool = False) -> dict[str, Any]:
    candidates = build_candidates_etf(vix_min=vix_min, vix_max=vix_max)
    print(f"Candidates: {len(candidates):,} across {candidates['symbol'].n_unique()} ETFs, "
          f"{candidates['date'].n_unique()} dates")

    trading_days: list[date] = sorted(candidates["date"].unique().to_list())
    vix_by_date: dict[date, float] = {
        r["date"]: float(r["vix"])
        for r in bt_data.load_macro().select("date", "vix").iter_rows(named=True)
    }

    portfolio = CspPortfolio(
        capital=starting_capital,
        stop_loss_premium_mult=stop_loss_mult,
        profit_target_frac=profit_target_frac,
    )
    cache = _ChainCache()
    equity_rows: list[dict] = []

    for i, today in enumerate(trading_days):
        vix = vix_by_date.get(today)
        if vix is None:
            raise KeyError(f"No VIX for {today}")

        _phase_a_manage(portfolio, today, vix, cache)
        portfolio.apply_portfolio_stops(today)

        day_candidates = candidates.filter(pl.col("date") == today)
        opened_per_day = _phase_c_enter(
            portfolio, today, day_candidates, cache,
            target_delta=target_delta, min_premium_yield=min_premium_yield,
        )

        snap = portfolio.snapshot(today)
        snap["n_opened"] = opened_per_day
        snap["n_candidates"] = day_candidates.height
        snap["vix"] = vix
        equity_rows.append(snap)

        if verbose and (i % 50 == 0 or i == len(trading_days) - 1):
            print(
                f"[{today}] cap=${portfolio.capital:,.0f} "
                f"reserved=${portfolio.notional_reserved:,.0f} "
                f"open={len(portfolio.open_positions)} "
                f"halt={portfolio.halted} trades={len(portfolio.trade_log)}"
            )

    # Force-close anything still open on the last day at the last mark.
    last_day = trading_days[-1]
    for pos in list(portfolio.open_positions):
        spot = cache.underlying_on(pos.symbol, pos.expiration_date) \
            or cache.underlying_on(pos.symbol, last_day) \
            or pos.underlying_price
        if spot is None:
            portfolio.notional_reserved -= pos.contract.notional_margin
            portfolio.open_positions.remove(pos)
            continue
        portfolio.settle_expiration(pos, float(spot))

    trade_log = pl.DataFrame(portfolio.trade_log) if portfolio.trade_log else pl.DataFrame()
    equity = pl.DataFrame(equity_rows)

    if save:
        Path(bt_data.OUTPUT_DIR).mkdir(parents=True, exist_ok=True)
        if trade_log.height > 0:
            trade_log.write_parquet(TRADE_LOG_FILE)
        equity.write_parquet(EQUITY_FILE)

    return {
        "n_trading_days": len(trading_days),
        "n_trades": trade_log.height,
        "starting_capital": starting_capital,
        "final_capital": portfolio.capital,
        "peak_capital": portfolio.peak_capital,
        "halted": portfolio.halted,
        "trade_log": trade_log,
        "equity_curve": equity,
        "summary_stats": _summary_stats(trade_log, equity, starting_capital),
    }


# ----- stats --------------------------------------------------------------

def _summary_stats(trade_log: pl.DataFrame, equity: pl.DataFrame,
                   starting_capital: float) -> dict[str, Any]:
    if trade_log.height == 0:
        return {
            "n": 0, "mean_net_pnl": 0.0, "win_rate": 0.0, "sharpe": 0.0,
            "max_drawdown": 0.0, "profit_factor": 0.0,
        }

    net = trade_log["net_pnl"].to_numpy()
    gross_wins = float(trade_log.filter(pl.col("net_pnl") > 0)["net_pnl"].sum())
    gross_losses = float(-trade_log.filter(pl.col("net_pnl") < 0)["net_pnl"].sum())

    eq = equity["capital"].to_numpy()
    daily_ret = (eq[1:] - eq[:-1]) / eq[:-1]
    sharpe = 0.0
    if daily_ret.size > 1 and daily_ret.std(ddof=1) > 0:
        sharpe = float(daily_ret.mean() / daily_ret.std(ddof=1) * (252 ** 0.5))

    peaks = 0.0
    mdd = 0.0
    for x in eq:
        peaks = max(peaks, x)
        if peaks > 0:
            mdd = max(mdd, (peaks - x) / peaks)

    exit_reason_counts = (
        trade_log.group_by("exit_reason")
        .agg(pl.len().alias("n"), pl.col("net_pnl").mean().alias("mean_net_pnl"))
        .sort("n", descending=True)
        .to_dicts()
    )
    per_symbol = (
        trade_log.group_by("symbol")
        .agg(
            pl.len().alias("n"),
            pl.col("net_pnl").mean().alias("mean_net_pnl"),
            (pl.col("net_pnl") > 0).mean().alias("win_rate"),
        )
        .sort("n", descending=True)
        .to_dicts()
    )

    return {
        "n": int(trade_log.height),
        "mean_net_pnl": float(net.mean()),
        "median_net_pnl": float(trade_log["net_pnl"].median()),
        "win_rate": float((net > 0).mean()),
        "avg_holding_days": float(trade_log["holding_days"].mean()),
        "sharpe": sharpe,
        "max_drawdown": mdd,
        "profit_factor": (gross_wins / gross_losses) if gross_losses > 0 else float("inf"),
        "total_commissions": float(trade_log["commission"].sum()),
        "exit_reason_counts": exit_reason_counts,
        "per_symbol": per_symbol,
    }


if __name__ == "__main__":
    import sys
    pt = None if "--no-pt" in sys.argv else 0.50
    res = run_level2_csp(verbose=True, profit_target_frac=pt)
    s = res["summary_stats"]
    print("\n=== Level 2 CSP Summary ===")
    print(f"  n_trades:      {s['n']}")
    print(f"  mean net PnL:  ${s['mean_net_pnl']:.2f}")
    print(f"  win rate:      {s['win_rate']:.1%}")
    print(f"  Sharpe:        {s['sharpe']:.2f}")
    print(f"  max drawdown:  {s['max_drawdown']:.1%}")
    print(f"  profit factor: {s['profit_factor']:.2f}")
    print(f"  final capital: ${res['final_capital']:,.0f}")
